<Project>
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Version>2.1.0</Version>
    <Authors>Tedd</Authors>
    <RepositoryUrl>https://github.com/tedd/Tedd.TcpTunnel</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
