<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="K4os.Compression.LZ4" Version="1.3.8" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <InternalsVisibleTo Include="Tedd.TcpTunnel.Tests" />
    <InternalsVisibleTo Include="Tedd.TcpTunnel.Benchmarks" />
  </ItemGroup>
</Project>
