<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="coverlet.MTP" Version="10.0.1" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Tedd.TcpTunnel.Console/Tedd.TcpTunnel.Console.csproj" />
    <ProjectReference Include="../Tedd.TcpTunnel/Tedd.TcpTunnel.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
