<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>tcptunnel</AssemblyName>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Tedd.TcpTunnel/Tedd.TcpTunnel.csproj" />
    <InternalsVisibleTo Include="Tedd.TcpTunnel.Tests" />
  </ItemGroup>
</Project>
