<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>tcptunnel</AssemblyName>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Tedd.TcpTunnel/Tedd.TcpTunnel.csproj" /><ProjectReference Include="../Tedd.TcpTunnel.Management/Tedd.TcpTunnel.Management.csproj" />
    <InternalsVisibleTo Include="Tedd.TcpTunnel.Tests" /><InternalsVisibleTo Include="Tedd.TcpTunnel.ControlPanel" />
  </ItemGroup>
</Project>
