<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
    <ProjectReference Include="../Tedd.TcpTunnel/Tedd.TcpTunnel.csproj" />
    <ProjectReference Include="../Tedd.TcpTunnel.Archive/Tedd.TcpTunnel.Archive.csproj" />
  </ItemGroup>
</Project>
