<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tedd.TcpTunnel\Tedd.TcpTunnel.csproj" />
    <ProjectReference Include="..\Tedd.TcpTunnel.Archive\Tedd.TcpTunnel.Archive.csproj" />
  </ItemGroup>

</Project>
